### ISSUE TITLE
error nuking and resetting aggregate branch with path based tag

### ISSUE THREAD

**Issue by wireframe** [wireframe/gitx#51]
```
$ git fetch --tags
Reset staging to builds/master/2017-06-01-13-46-46? (y/n) y
$ git diff builds/master/2017-06-01-13-46-46...staging --name-only db/migrate
fatal: ambiguous argument 'builds/master/2017-06-01-13-46-46...staging': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
/Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gitx-3.0.1/lib/gitx/executor.rb:23:in `block in execute': git diff builds/master/2017-06-01-13-46-46...staging --name-only db/migrate failed (Gitx::Executor::ExecutionError)
	from /Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open3.rb:205:in `popen_run'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/2.4.0/open3.rb:190:in `popen2e'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gitx-3.0.1/lib/gitx/executor.rb:14:in `execute'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gitx-3.0.1/lib/gitx/cli/base_command.rb:26:in `run_cmd'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gitx-3.0.1/lib/gitx/cli/base_command.rb:32:in `run_git_cmd'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gitx-3.0.1/lib/gitx/cli/nuke_command.rb:37:in `migrations_need_to_be_reverted?'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gitx-3.0.1/lib/gitx/cli/nuke_command.rb:18:in `nuke'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gitx-3.0.1/bin/git-nuke:6:in `<top (required)>'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/bin/git-nuke:22:in `load'
	from /Users/ryansonnek/.rbenv/versions/2.4.1/bin/git-nuke:22:in `<main>'
```

**Comment by wireframe** [comment]
not able to reproduce.
